name: pipecat-whisperx
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch-cuda=12.4
  - pytorch
  - torchaudio
  - ffmpeg
  - portaudio
  - pip
  - pip:
    - pipecat-ai[local]
    - whisperx
    - python-dotenv
    - websockets
    - sounddevice
